import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  overviewSidebar: [
    'overview/project-overview',
    {
      type: 'category',
      label: 'Functionality',
      items: [
        'overview/functions-specifications',
        'overview/fee-structure',
        'overview/shareholder-revenues',
        'overview/coin',
      ],
    },
    'overview/package',
  ],

  exploreSidebar: [
    'explore/a-guide-to-nft-trading-platforms',
    {
      type: 'category',
      label: 'How to',
      items: [
        'explore/connect-your-wallet',
        'explore/create-a-collection',
        'explore/create-nft',
        'explore/list-nfts',
        'explore/buy-nfts',
        'explore/exchange',
        'explore/auction',
      ],
    },
  ],

  faqSidebar: [
    'faq/faq'
  ],
   
};

export default sidebars;
